### ISSUE TITLE
GuessGame: informe número de tentativas errado no final

### ISSUE THREAD

**Issue by f-t-alves** [monclarluiz/EstudoAutomateBoringStuff#1]
O jogo está informando o meu último chute ao invés da quantidade de chutes dado.

![image](https://user-images.githubusercontent.com/34032396/114191632-01eac400-9923-11eb-9145-86658c6a19dd.png)

**Comment by monclarluiz** [comment]
Ele enviava "tentativas" ao invés do "tentativasfeitas". Valeu, Fábio!
